# Generated by Django 5.0.1 on 2024-02-01 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='book_detail',
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.book'),
            preserve_default=False,
        ),
    ]
